# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr

addons:
  apt:
    update: true
    packages:
      - libglpk-dev


after_success:
  - Rscript -e 'library(covr); codecov()'

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=true
